config/routes.rb
Rails.application.routes.draw do

  get 'results', to: 'search#results'
  
  get 'tags', to: "tags#index", as: :tags

  resources :comments, only: [:destroy, :create]
  resources :answers, except: [:index]
  resources :questions 
  
  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }
  get 'profile/:username', to: 'users#show', as: :user
  resources :users, only: []
  
  root "questions#index"
  
  
  
  

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!, only: [:results]
  respond_to :html
  
  # Displays search results.
  # Gets search results based on search query and paginates.
  # If no results, redirect to root path with flash message about no results else display.
  def results
    @results = PgSearch.multisearch(params[:search_query]).preload(:searchable).page(params[:page])
    if @results.empty?
      # Use controller to create form and use methods to create search and then display results. Keep sepereate from question display/ integrate into DRY 
      flash[:alert] = "No results."
      redirect_to questions_path
    else
      render :results
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
  
  # Helper that displays search results titles.
  # Ex. output: Question: this is a question title
  #             <p>Truncated HTML of question text</p>
  # Grabs length for HTML from en.yml.
  def display_title_helper(searchObj)
    result = searchObj.searchable_type + ": "
    if searchObj.searchable_type == "Question"
      title = searchObj.searchable.title
      text = searchObj.searchable.question_text
      length = t('general.char_display.question')
    else
      title = searchObj.searchable.question.title
      text = searchObj.searchable.answer_text
      length = t('general.char_display.answer')
    end
    result = "<strong>" + result + link_to(title, searchObj.searchable).html_safe + "</strong>"
    result = result + "<br />" + truncate_html(text, length: length).html_safe
    return result.html_safe
  end
  
  # Helper that displays 'extra' info for search results.
  # At the moment this helper delegates the display of tags to the question helper.
  # No output for answers.
  def display_extra_helper(searchObj)
    #TODO  make display more data, make third helper for the side of the result
    case searchObj.searchable_type
      when "Question"
        result = question_tag_display_helper(searchObj.searchable)
      when "Answer"
        result = ""
      else
      result =  ""
    end
    return result.html_safe
  end
  
  # Helper that displays postre info.
  # Method delegates to the respective helpers for each model and then returns result.
  def display_poster_info_helper(searchObj)
    case searchObj.searchable_type
      when "Question"
        result = question_display_poster_info_helper(searchObj.searchable)
      when "Answer"
        result = answer_display_poster_info_helper(searchObj.searchable)
      else
      result =  ""
    end
    return result.html_safe
  end
end

app/views/search/_search_bar.html.erb
<!--Search bar partial to display the seatch bar on any page -->
<div class="row">
    <div class="large-12 columns">
      <%= form_tag(results_path, method: "get") do %>
      <div class="row collapse">
        <div class="small-10 columns">
          <%= search_field_tag :search_query, nil, placeholder: 'Search...' %>
        </div>
        <div class="small-2 columns">
          <%= submit_tag "Search", class: "button postfix" %>
        </div>
      </div>
      <% end %>
    </div>
</div>

app/views/search/results.html.erb
<!--Results page from a search - shows both questions and answers -->
<%= provide(:title, t('page_titles.search_results')) %>
<%= render 'search_bar' %>
<!-- Pagination info -->
<%= page_entries_info @results, :entry_name => t('general.model_names.search_result') %>
<%= paginate @results%> 
<hr />
<% @results.each do |r| %>
<!-- result display helper  -->
<%= render 'shared/result_display', display_title: display_title_helper(r), display_extra: display_extra_helper(r), display_poster_info: display_poster_info_helper(r) %>

<hr />

<% end %>

<%= paginate @results%>