config/routes.rb
Rails.application.routes.draw do

  get 'results', to: 'search#results'
  
  get 'tags', to: "tags#index", as: :tags

  resources :comments, only: [:destroy, :create]
  resources :answers, except: [:index]
  resources :questions 
  
  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }
  get 'profile/:username', to: 'users#show', as: :user
  resources :users, only: []
  
  root "questions#index"
  
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Devise
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Non-model fields
  attr_accessor :delete_image
  
  # Validations
  validates :username, presence: true
  validates :username, :uniqueness => { :case_sensitive => false}
  validates :email, :uniqueness => { :case_sensitive => false}
  validate :real_username_choice
  validate :username_valid
  
  # Callbacks
  before_save :sanitize_user
  before_validation  :delete_image?
  
  # Relationships
  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :visits, dependent: :destroy
  has_many :ahoy_events, class_name: "Ahoy::Event", dependent: :destroy
  
  # Paperclip
  # Avatar attached to User
  has_attached_file :avatar, styles: {
    thumb: '50x50#',
    small: '150x150#',
    }, path: ":username/avatar/:style/:basename.:extension", :default_url => ""
    
  # Validations
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # No huge images allowed
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes 
  
  # Method to check if either the first name or last name or both are blank.
  def first_last_blank?
    self.first_name.blank? || self.last_name.blank?
  end
  
  # Method that outputs the users preffered name. 
  # Checks that pref_name is 'real' for real name and that neither the first or last name is blank.
  # Else if check fails then returns the username. 
  def output_name
    if self.pref_name == "real" && !self.first_last_blank?
      "#{self.first_name} #{self.last_name}"
    else
      self.username
    end
  end
  
  # Method that sanitizes the user summary to make sure no script tags get through.
  def sanitize_user
    self.user_summary = html_sanitizer(self.user_summary)
  end
  
  # Method that checks whether the user selected to delete their current image. 
  # If so then deletes it. 
  # Users will use this when they want to delete their image but not upload a new one. 
  def delete_image?
    if self.delete_image == "1"
      self.avatar = nil
    end
  end
  
  # Validation check
  # Checks that IF pref_name is 'real' that neither the first or last name is blank
  # If they are then an error will appear.
  def real_username_choice
    if self.pref_name == "real" && first_last_blank?
      errors.add(:pref_name, "First and Last name must be filled in")
    end
  end
  
  # Validation check
  # 
  def username_valid
    if(!self.username.nil? && self.username.include?("."))
      errors.add(:username, "Username cannot contain: '.'")
    end
  end
  
  # Method that allows for the usage of :username in the paperclip path
  Paperclip.interpolates :username do |attachment, style|
   attachment.instance.username
  end
  
  
  # These 3 methods are used to allow users to sign in using either username or email
  # Devise
  def login=(login)
    @login = login
  end
  # Devise
  def login
    @login || self.username || self.email
  end
  # Devise
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
  # Devise
  # This method takes advantage of active job to queue emails to be sent later when available resources exist
  def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
    UserMailer.welcome_email(resource.id).deliver_later! unless resource.id.nil?
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # Gets the default edit action for Devise
  def edit
    super
  end

  # PUT /resource
  # Uses the default update action of Devise but also sets the 'output_name' in session so user sees the change (if changed) 
  def update
    super
    ahoy.track "private_edit_profile"
    if resource.encrypted_password_changed?
      ahoy.track "private_changed_password"
    end
    session["output_name"] = resource.output_name
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :avatar
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  
  # The path to redirect to upon successful profile update
  def after_update_path_for(resource)
    user_path(resource.username)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_before_action :authenticate_user!, only: [:show]
  respond_to :html
  
  # Displays user profile page.
  def show
    ahoy.track "public_view_profile", id: @user.id
    respond_with @user
  end


  private
  
  # Sets user and includes their questions and answers. Use username to find users.
  def set_user
    @user = User.includes(:questions, :answers).find_by_username(params[:username])
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Helper that displays avatar and links for delete/add.
    def profile_avatar_helper(user, form)
        if !user.nil? && !form.nil? && user.class == User
           return_string = ""
           label_string = "Profile Image"
          delete_label = "Delete Profile Image?"
            if !user.avatar_file_name.nil?
               return_string = image_tag(user.avatar.url(:thumb), alt: "Current Profile Image")
               return_string += form.input :delete_image, label: delete_label, as: :boolean 
               label_string = "Update Profile Image"
            end
           return_string += form.input :avatar, required: false, label: label_string, as: :file
        end
           return_string.html_safe
    end
    
    # Helper that displays the users avatar on profile page.
    # If there is no profile page then image displayed would be generic image.
    def avatar_display_helper
      #TODO remove instance variable and replace with parameter
        if !@user.avatar_file_name.nil?
             image_tag(@user.avatar.url(:small), alt: "#{@user.output_name} profile image") 
        else
            # If no default profile image then provide default. (From out site so more secure)
           image_tag('profile_placeholder.png', alt: "No profile image selected.", size: "140x150")
        end
    end
end

app/views/users/show.html.erb
<!--Profile show/view page - shows users questions, answers, and other activity as well as summary and other info -->
<% provide(:title, t('page_titles.models.user.show', output_name: @user.output_name)) %>
<div class="row">
  <div class="small-9 columns">
    <h2><%= @user.output_name %></h2>
  </div>
  <div class="small-3 columns">
    <% if policy(@user).edit? %>
    <p><%= link_to "Edit", edit_registration_path(@user) %></p>
    <% end %>
    <% if current_user != nil && current_user != @user %>
    <p>Report</p>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="large-4 columns">
    <!-- display image -->
    <%= avatar_display_helper %>
  </div>
  <div class="large-8 columns">
    <table style="border: none; background-color: transparent;">
<!--    quick info about user    -->
      <tr>
        <td>Questions: <%= @user.questions.count %></td>
        <td>Member since: <%= @user.created_at.strftime("%B %d, %Y") %></td>
      </tr>
      <tr style="background-color: transparent;">
        <td>Answers: <%= @user.answers.count %></td>
        <td></td>
      </tr>
      <tr>
        <td></td> <!-- TODO questions contributed to  contributions uniq by question id (avoid doubel counting of answers and coments on same question)     -->
        <td></td>
      </tr>
    </table>
  </div>
</div>
<br />
<div class="row">
  <div class="small-12 columns">
    <h3>About <%= @user.output_name %></h3>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <%= !@user.user_summary.nil? ? @user.user_summary.html_safe : "Nothing here yet..." %>
  </div>
</div>
<br />
<br />
<!-- Questions, answers and activity tabs -->
<div class="row">
  <div class="small-12 columns">
    <dl class="tabs" data-tab>
  <dd class="active"><a href="#questions_panel">Questions</a></dd>
  <dd><a href="#answers_panel">Answers</a></dd>
  <dd><a href="#activity_panel">Activity</a></dd>
</dl>
<div class="tabs-content">
  <div class="content active" id="questions_panel">
    <% if @user.questions.count != 0 %>
    <% @user.questions.each_with_index do |q, i| %>
        <div class="row">
          <div class="small-2 columns">
<!--        can put other info here like # of answers or something... not sure yet      -->
          </div>
          <div class="small-10 columns">
            <%= link_to q.title, q %>
          </div>
        </div>
     <div class="row">
       <div class="small-12 columns">
            <hr />
       </div>
    </div>
      <% end %>
    <% else %>
    <p>This user has not asked any questions yet.</p>
    <% end %>
  </div>
  <div class="content" id="answers_panel">
    <% if @user.answers.count != 0 %>
    <% @user.answers.includes(:question).each_with_index do |a, i| %>
        <div class="row">
          <div class="small-2 columns">
<!--        can put other info here like # of upvotes or something... not sure yet      -->
          </div>
          <div class="small-10 columns">
            <%= link_to a.question.title, question_path(a.question, anchor: "answer-#{a.id}") %>
          </div>
        </div>
     <div class="row">
       <div class="small-12 columns">
            <hr />
       </div>
    </div>
      <% end %>
    <% else %>
    <p>This user has not answered any questions yet.</p>
    <% end %>
  </div>
  <div class="content" id="activity_panel">
    <p>No user activity yet</p>
  </div>
</div>
  </div>
</div>