config/routes.rb
Rails.application.routes.draw do

  get 'results', to: 'search#results'
  
  get 'tags', to: "tags#index", as: :tags

  resources :comments, only: [:destroy, :create]
  resources :answers, except: [:index]
  resources :questions 
  
  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }
  get 'profile/:username', to: 'users#show', as: :user
  resources :users, only: []
  
  root "questions#index"
  
  
  
  

end

app/views/layouts/app_layout/_footer.html.erb
<!--Footer of application template -->
<div class="row">
    <div class="large-12 columns">
         <hr />
         <br />
        <%= link_to "Home", root_path %> &nbsp;
        <%= link_to "All Questions", root_path %> &nbsp;
    </div>
</div>


<!--Debug info for Development -->
<%= debug(params) if Rails.env.development? %>

app/views/layouts/app_layout/_menu_bar.html.erb
<!--Menu bar for application template. --> 
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Accounting Studies", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      
      <li class="has-dropdown">
        <%= link_to "Questions", root_path %>
       <ul class="dropdown">
         <li><%= link_to "Ask a Question", new_question_path %></li>
         <li><%= link_to "View all Questions", root_path %></li>
         <li><%= link_to "View all Tags", tags_path %></li>
        </ul>
      </li>
      
      <li><%= link_to "Calculator", root_path(flash: "Feature coming soon!") %></li>
      
      <li><%= link_to "About us", root_path(flash: "About us coming soon!") %></li>
      
      <li class="has-dropdown">
        <%= link_to "Help", root_path %>
        <ul class="dropdown">
          <li><%= link_to "Question Asking Guide", root_path(flash: "Guide coming soon!") %></li>
          <li><%= link_to "Tour", root_path(flash: "Tour coming soon!") %></li>
          <li><%= link_to "Site Policies", root_path(flash: "Site policies coming soon!") %></li>
        </ul>
      </li>
      
      <% if !current_user.nil? %>
      
      <li class="has-dropdown">
        <%= link_to "Logged in as #{session["output_name"] || current_user.output_name}", user_path(current_user.username) %>
        <ul class="dropdown">
          <li><%= link_to "Profile", user_path(current_user.username) %></li>
          <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
        </ul>
      </li>
      
      <% else %>
      
      <li class="has-dropdown">
        <%= link_to "Log in", new_user_session_path %>
      <ul class="dropdown">
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        </ul>
      </li>
      
      <% end %>
      
    </ul>
  </section>
</nav>

app/views/layouts/app_layout/_notification.html.erb
<!-- Flash displayer for application template. This partial handles all the flash[*] messages and formats them nicely. -->
 <% flash.each do |message_type, message| %>
        <div  data-alert id="<%= message_type %>_1" class="<%= flash_class(message_type) %>" tabindex="0" aria-live="assertive" role="dialogalert"><%= message %>
        <a href="#" class="close">&times;</a>
          </div>
      <% end %>