config/routes.rb
Rails.application.routes.draw do

  get 'results', to: 'search#results'
  
  get 'tags', to: "tags#index", as: :tags

  resources :comments, only: [:destroy, :create]
  resources :answers, except: [:index]
  resources :questions 
  
  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }
  get 'profile/:username', to: 'users#show', as: :user
  resources :users, only: []
  
  root "questions#index"
  
  
  
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  # PgSearch include to provide methods
  # Multisearchable to be able to search multiple models at once. Searches on answer_text only.
  # Orders to provide consistency in output (and correct pagination).
  include PgSearch
  multisearchable :against => :answer_text, :order_within_rank => "answers.updated_at DESC"
  
  # Validiations
  validates :user_id, :question_id, :answer_text, presence: true
  
  # Callbacks
  before_save :sanitize_answer
  
  # Scopes
  default_scope {includes(:user, :question)}
  
  # Relationships
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_one :spread_sheet_upload, as: :attachable, dependent: :destroy
  
  # Relationship modifiers
  accepts_nested_attributes_for :spread_sheet_upload, allow_destroy: true # Needs to be able to edit/delete its spread_sheet_upload.
    
  # Method that returns the answer's question (if marked as correct answer) or false (if not)
  def correct?
    Question.find_by(id: self.correct_answer_id) || false
  end
  
  # Method that is used to return the answer's spread sheet upload or a new spread sheet upload object.
  def get_spread_sheet_upload
    return self.spread_sheet_upload || self.build_spread_sheet_upload
  end
  
  # Method that takes a answers text and sanitizes it to remove JS
  def sanitize_answer
    self.answer_text = html_sanitizer(self.answer_text)
  end
 
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:edit, :update, :destroy, :show]
  skip_before_action :authenticate_user!, only: [:show]
  respond_to :html
  
  # Shows a new answer after failed validation.
  # Used to render the new page in case of validation error so that user can fix their mistakes. 
  # WILL NOT work to go alone because requires @question variable to be set.
  def new
  end
  
  
  # Shows an answer.
  # Show method simplifies getting to a specific answer. Since Answer has no show page of its own
  # it will grab its question and link to an anchor (in the page for each answer) so that when 
  # clicked it it takes user to that part of the page.
  def show
    redirect_to question_path(@answer.question, anchor: "answer-#{@answer.id}")
  end
 
  # Creates an answer
  # Requires a user to be signed in otherwise cannot build the answer off of the current_user.
  # On successful creation a success flash with the appropriate message is displayed. Will redirect to the answers question.
  # Will also send email to let question owner know that answer has been posted.
  # On creation failure redirect to answer new to fix errors.
  def create
    @answer = current_user.answers.build(answer_params)
    if @answer.save
      flash[:success] = t('messages.models.general.post', model: "Answer")
      ahoy.track "public_created_answer", id: @answer.id
      PostableMailer.new_answer_on_post_email(@answer.question, @answer).deliver_later!
      redirect_to question_path(@answer.question)
    else
      respond_with(@answer)
    end
  end
  
  # Edit an answer.
  # Authorizes user to edit question.
  # Assigns answers @question to display while editing.
  def edit
    authorize(@answer)
    @question = @answer.question
  end
  
  # Destroys an answer.
  # Authorizes to assure can destroy.
  # Gets the answers question for after delete redirect.
  # Destroys the answer and then sets the flash to appropriate text.
  def destroy
    authorize(@answer)
    q = @answer.question
    aId = @answer.id
    @answer.destroy
    flash[:success] = t('messages.models.general.delete', model: "Answer")
    ahoy.track "public_created_answer", id: aId
    redirect_to question_path(q)
  end
  
  # Updates an answer.
  # Authorizes the user to make sure they can edit.
  # Depending on if update is for marking an answer correct or just updating an answer the flash will change.
  # Once successful update redirect to answers question. 
  # If fail update redirect to fix answer issue. 
  # Should never be an issue with updating the correctness of the answer (hopefully).
  def update
    if answer_params.has_key?("correct_answer_id") && (answer_params.length == 1)
      authorize(@answer, :can_select_correct_answer?)
      @answer.question.correct_answer = nil
      answer_flash =  t('messages.models.answer.marked_correct')
    else
      authorize(@answer)
      answer_flash = t('messages.models.general.update', model: "Answer")
    end
    if @answer.update(answer_params)
      flash[:success] = answer_flash
      ahoy.track "public_updated_answer", id: @answer.id
      redirect_to question_path(@answer.question)
    else
      respond_with(@answer)
    end
  end
  
  
private
  # Sets the answer, reduces code duplication.
  def set_answer
    @answer = Answer.find(params[:id])
  end
  
  #  Strong params, the params that are let through to be processed. Prevents malicious addition of additional params.
  def answer_params
    params.require(:answer).permit(:id, :answer_text, :question_id, :user_id, :correct_answer_id, :spread_sheet_upload_attributes => [:id, :sheet, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
   
  # Helper to display the post and posters info:
  # Returns HTML string like this wrapped in a div: Answered: May 5 2015 by UserName
  def answer_display_poster_info_helper(answer)
    return_result = content_tag :div, class: "answer_results" do
      concat content_tag(:span, 
      "Answered: #{formatted_created_at(answer)} by #{link_to(answer.user.output_name, user_path(answer.user.username))}".html_safe)
    end
    return return_result.html_safe
  end
  
  # Helper to provide output for if can post an answer. Sets placeholder.
  def answer_input_text_helper(answer)
    if policy(answer).can_post?
      ""
    else
      "Must be signed in to post answers."
    end
  end
  
  # Helper that determines if tinymce loads.
  def answer_text_box_helper(answer)
    if policy(answer).can_post?   
      "tinymce"
    else
      ""
    end
  end
  
  # Helper that determines if it should display a checkmark to signify that the answer is marked as correct.
  def answer_correct_checkmark_display_helper(answer)
    output = ""
    if !answer.correct_answer_id.nil?
      output = content_tag :h1 do 
              concat "<span data-tooltip aria-haspopup=\"true\" 
              class=\"has-tip\" title=\"#{t('general.answer.marked_correct')}\">
              <i class=\"fi-check\"></i></span>".html_safe
      end
    end
    return output.html_safe
  end
 
  # Helper that displays the answer posters information on the question 'show' page.
  # TODO add row for 'Updated: {date}' to show last update
  def answer_poster_info_question_show(answer)
    output = content_tag :div, class: "panel" do
        concat "Answered: #{answer.created_at.strftime("%m/%d/%y %H:%M")}
        <br />
        Answered by: #{link_to answer.user.output_name, user_path(answer.user.username)}".html_safe
    end
    output.html_safe
  end
  
  # Helper that will create the form that a user can use to mark an answer correct.
  def answer_mark_answer_correct_form_helper(answer, question)
    # previous
    #     <% if answer.correct_answer_id.nil? && policy(answer).can_select_correct_answer? %>
    #   <%= simple_form_for(answer) do |f|%>
    #   <%= f.input :correct_answer_id, as: :hidden,  :input_html => { :value => @question.id } %>
    #   <%= link_to 'Mark answer as correct <i class="fi-check"></i>'.html_safe, "#", :onclick => "$('#edit_answer_#{answer.id}').submit()" %>
    #   <% end %>
    # <% end %>
    output = ""
    if answer.correct_answer_id.nil? && policy(answer).can_select_correct_answer?
      output = simple_form_for(answer) do |f|
          f.input :correct_answer_id, as: :hidden,  :input_html => { :value => question.id }
          link_to 'Mark answer as correct <i class="fi-check"></i>'.html_safe, "#", :onclick => "$('#edit_answer_#{answer.id}').submit()"
      end
    end
  end
end

app/views/answers/_answer.html.erb
   <!-- HR for to seperate from anything above the answer partial. -->
  <div class="row">
    <div class="small-offset-1 small-11 columns"> 
      <hr />
    </div>
  </div>
<!-- Create anchor tag for partial (for easier linking) -->
<a href="#answer-<%= answer.id %>"></a>
<div class="row"  id="answer-<%= answer.id %>">
  <div class="small-1 columns"> 
  <!-- Need this cause if no content in column others move into the column. -->
  &nbsp; 
  <!-- If answer marked correct show big checkmark to signify it. -->
    <%= answer_correct_checkmark_display_helper(answer) %>
  </div>
  <div class="small-8 columns"> 
  <!-- Displays the content of the answer and associated spread sheet upload if has one -->
    <%= answer.answer_text.html_safe %> 
    
    <%= spread_sheet_upload_download_display_helper(answer) %> 
  </div>
  
  <div class="small-3 columns">
    <!-- This is the side column it shows the answers poster info (like date and who) as well as has links for edit/delete/report. -->
    <%= answer_poster_info_question_show(answer) %>

    <%= link_to "Edit", edit_answer_path(answer)  if policy(answer).edit? %> 
  
    <%= link_to "Delete", answer, method: :delete, data: { confirm: 'Are you sure?' }  if policy(answer).destroy?%>
    
    <br />
    <!-- If the question owner is logged in then they get a form to choose the correct answer. -->
    <%= answer_mark_answer_correct_form_helper(answer, @question) %>
  </div>
</div>
<div class="row">
  <div class="small-offset-1 small-11 columns"> 
    <hr />
  </div>
</div>

<!-- Show the answers comments and create a new comment form -->
 <%= render answer.comments.default_order %>
 <%= render "comments/new_comment", :passed => answer %>

app/views/answers/_form.html.erb
<!-- Form for new or editing answer. -->
<%= simple_form_for(@answer) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
      <!-- Answer text input field. This field will be enabled or disabled depending on if one can post or not. -->
    <%= f.input :answer_text, required: false, label: false, placeholder: answer_input_text_helper(@answer),  :disabled => !policy(@answer).can_post?, input_html: {class: answer_text_box_helper(@answer), rows: 15} %>
       <!-- Hidden Question ID field that will make sure the answer is linked to the correct question. -->
    <%= f.input :question_id, as: :hidden,  :input_html => { :value => question.id } %>
    <!-- Upload file helper -->
    <%= render "shared/file_upload_form", :f => f, :attached_file => @answer.get_spread_sheet_upload%>
  </div>
<br />
<!-- Preview notice for users to know how to see what their answer looks like before they post. -->
<%= render "shared/tinymce_preview_notice" %>
<!-- Submit button motified to whether is second/ more post for user and if can post or not. -->
   <div class="form-actions">
     <% if policy(@answer).second_post? %>
     <%= f.button :submit, data: {confirm: t('general.amswer.second_post')} %>
     <% else %>
      <%= f.button :submit, class: "button "+button_class_helper(@answer) %>
     <% end %>
  </div>
<% end %>

app/views/answers/_new_answer.html.erb
<!-- new answer is just a partial that reneders the form and links the associated question. -->
<%= render 'answers/form', :question => question %>

app/views/answers/edit.html.erb
<!--Full edit page with title, show of the question being edited and the form for the answer. -->
<%= provide(:title, t('page_titles.models.general.edit', model: @answer.class.to_s)) %>
<%= render "questions/show_question", :question => @answer.question %>

<label>Edit Answer</label>
<%= render 'answers/form', :question => @answer.question %>

app/views/answers/new.html.erb
<!--Full new form for if there is an error in first submit. -->
<%= provide(:title, t("page_titles.models.general.new", model: @answer.class.to_s)) %>
<!-- Show the question and form for the answer. -->
<%= render "questions/show_question", :question => @answer.question %>

<label>New Answer</label>
<%= render 'answers/form', :question => @answer.question %>